export enum TipoUsuario {
  CIDADAO = 'CIDADAO',
  ENTIDADE = 'ENTIDADE',
  POLITICO = 'POLITICO',
  IMPRENSA = 'IMPRENSA',
  ONG = 'ONG',
  PESQUISADOR = 'PESQUISADOR',
  MODERADOR = 'MODERADOR',
  ADMIN = 'ADMIN',
}

export enum StatusRelato {
  ABERTO = 'ABERTO',
  EM_ANALISE = 'EM_ANALISE',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  RESOLVIDO = 'RESOLVIDO',
  CONTESTADO = 'CONTESTADO',
  ARQUIVADO = 'ARQUIVADO',
}

export enum TipoEvento {
  CRIADO = 'CRIADO',
  RESPONDIDO = 'RESPONDIDO',
  STATUS_ALTERADO = 'STATUS_ALTERADO',
  CONTESTADO = 'CONTESTADO',
  RESOLVIDO = 'RESOLVIDO',
  ARQUIVADO = 'ARQUIVADO',
}

export enum Categoria {
  SAUDE = 'SAUDE',
  MOBILIDADE = 'MOBILIDADE',
  SEGURANCA = 'SEGURANCA',
  EDUCACAO = 'EDUCACAO',
  SANEAMENTO = 'SANEAMENTO',
  HABITACAO = 'HABITACAO',
  OUTROS = 'OUTROS',
}

export enum TipoEntidade {
  PREFEITURA = 'PREFEITURA',
  HOSPITAL = 'HOSPITAL',
  CONCESSIONARIA = 'CONCESSIONARIA',
  AUTARQUIA = 'AUTARQUIA',
  SECRETARIA = 'SECRETARIA',
  OUTROS = 'OUTROS',
}

export enum DestinatarioTipo {
  ENTIDADE = 'ENTIDADE',
  EMPRESA = 'EMPRESA',
  FILIAL = 'FILIAL',
  POLITICO = 'POLITICO',
}

export enum SetorEmpresa {
  TELECOM = 'TELECOM',
  SAUDE_SUPLEMENTAR = 'SAUDE_SUPLEMENTAR',
  FINANCEIRO = 'FINANCEIRO',
  ENERGIA = 'ENERGIA',
  TRANSPORTE = 'TRANSPORTE',
  VAREJO = 'VAREJO',
  ALIMENTACAO = 'ALIMENTACAO',
  CONDOMINIO = 'CONDOMINIO',
  OUTROS = 'OUTROS',
}

export enum PorteEmpresa {
  MEI = 'MEI',
  PEQUENA = 'PEQUENA',
  MEDIA = 'MEDIA',
  GRANDE = 'GRANDE',
}

export enum PlanoEmpresa {
  STARTER = 'STARTER',
  BUSINESS = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
  WHITE_LABEL = 'WHITE_LABEL',
}

export enum TipoVoto {
  APOIO = 'APOIO',
  EU_TAMBEM = 'EU_TAMBEM',
}
