export enum UserType {
  CITIZEN = 'CITIZEN',
  ENTITY = 'ENTITY',
  POLITICIAN = 'POLITICIAN',
  PRESS = 'PRESS',
  NGO = 'NGO',
  RESEARCHER = 'RESEARCHER',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN',
}

export enum ReportStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  DISPUTED = 'DISPUTED',
  ARCHIVED = 'ARCHIVED',
}

export enum EventType {
  CREATED = 'CREATED',
  RESPONDED = 'RESPONDED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  DISPUTED = 'DISPUTED',
  RESOLVED = 'RESOLVED',
  ARCHIVED = 'ARCHIVED',
}

export enum Category {
  HEALTH = 'HEALTH',
  MOBILITY = 'MOBILITY',
  SAFETY = 'SAFETY',
  EDUCATION = 'EDUCATION',
  SANITATION = 'SANITATION',
  HOUSING = 'HOUSING',
  ENVIRONMENT = 'ENVIRONMENT',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  URBAN_SERVICES = 'URBAN_SERVICES',
  CORRUPTION = 'CORRUPTION',
  ACCESSIBILITY = 'ACCESSIBILITY',
  SOCIAL_WELFARE = 'SOCIAL_WELFARE',
  OTHER = 'OTHER',
}

export enum EntityType {
  CITY_HALL = 'CITY_HALL',
  HOSPITAL = 'HOSPITAL',
  CONCESSIONAIRE = 'CONCESSIONAIRE',
  AUTARCHY = 'AUTARCHY',
  SECRETARIAT = 'SECRETARIAT',
  OTHER = 'OTHER',
}

export enum RecipientType {
  ENTITY = 'ENTITY',
  COMPANY = 'COMPANY',
  BRANCH = 'BRANCH',
  POLITICIAN = 'POLITICIAN',
}

export enum CompanySector {
  TELECOM = 'TELECOM',
  SUPPLEMENTAL_HEALTH = 'SUPPLEMENTAL_HEALTH',
  FINANCIAL = 'FINANCIAL',
  ENERGY = 'ENERGY',
  TRANSPORTATION = 'TRANSPORTATION',
  RETAIL = 'RETAIL',
  FOOD = 'FOOD',
  CONDOMINIUM = 'CONDOMINIUM',
  OTHER = 'OTHER',
}

export enum CompanySize {
  MEI = 'MEI',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
}

export enum CompanyPlan {
  STARTER = 'STARTER',
  BUSINESS = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
  WHITE_LABEL = 'WHITE_LABEL',
}

export enum VoteType {
  SUPPORT = 'SUPPORT',
  ME_TOO = 'ME_TOO',
}
